version: '3'
services:
  consul:
    image: consul
  api-gateway:
    container_name: api_gateway_service
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - "consul"
  enigmi:
    container_name: enigmi_service
    build: ./enigmi
    depends_on:
      - "consul"
      - "kafka"
  connessioni:
    container_name: connessioni_service
    build: ./connessioni
    depends_on:
      - "consul"
  enigmi-seguiti:
    container_name: enigmi-seguiti_service
    build: ./enigmi-seguiti
    depends_on:
      - "consul"
  db_enigmi: 
    container_name: postgres_db_enigmi 
    image: postgres 
    volumes: 
    -   enigmi:/var/lib/postgresql/data 
    ports: 
    -   "5433:5432" 
    environment: 
        POSTGRES_USER: postgres 
        POSTGRES_PASSWORD: postgres 
        POSTGRES_DB: enigmi
  db_connessioni: 
    container_name: postgres_db_connessioni
    image: postgres 
    volumes: 
    -   connessioni:/var/lib/postgresql/data 
    ports: 
    -   "5434:5432" 
    environment: 
        POSTGRES_USER: postgres 
        POSTGRES_PASSWORD: postgres 
        POSTGRES_DB: connessioni
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - "zookeeper"
    ports:
      - "9092:9092"
    environment:
#       - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
#       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
#       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://10.11.121:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS="enigmi-event-channel:2:1, connessioni-event-channel:2:1"
    volumes:
      -   /var/run/docker.sock:/var/run/docker.sock
volumes:
  enigmi:
    external: true
  connessioni:
    external: true
  enigmi-seguiti:
    external: true
