version: '3'
services:
  consul:
    image: consul
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - "consul"
  enigmi:
    build: ./enigmi
    depends_on:
      - "consul"
  connessioni:
    build: ./connessioni
    depends_on:
      - "consul"
  enigmi-seguiti:
    build: ./enigmi-seguiti
    depends_on:
      - "consul"
volumes:
  enigmi:
    external: true
  connessioni:
    external: true
  enigmi-seguiti:
    external: true